### ISSUE TITLE
Add function to send and receive json

### ISSUE THREAD

**Issue by MohamedLEGH** [issuu/ocaml-zmq#112]
Hello,
I think it can be a good thing to add a function to send and receive json, like this function in the pyzmq library: https://pyzmq.readthedocs.io/en/latest/api/zmq.html#zmq.Socket.send_json

We can use the YoJson.Safe module : https://ocaml-community.github.io/yojson/yojson/Yojson/Safe/index.html

What do you think ? I can try to implement it if you want

**Comment by Leonidas-from-XIV** [comment]
Hi @MohamedLEGH, thanks for the ticket. In Python the situation is a bit different:

1. `json` is part of the standard library. While being a co-maintainer of Yojson, I don't think Yojson is as universal as that in OCaml
2. Python objects can be (sorta) serialized to arbitrary JSON. This is not true for OCaml, where one would need to use something like ppx_deriving_yojson to convert between (somewhat arbitrary) OCaml data structures and JSON.

As such I am not sure what kind of JSON integration you would require. The only thing that would be sensible is taking a value of `Yojson.Safe.t` and converting it to a string to be sent, but Yojson already comes with such a function (`Yojson.Safe.to_string`).

**Comment by MohamedLEGH** [comment]
Hello Leonidas,
Thanks for your answer.
Ok I thought that converting `Yojson.Safe.t` to binary data (with something like Marshal https://ocaml.org/api/Marshal.html) and sending it will allow to compress the amount of data to send.

I'm a newbie to Ocaml so don't hesitate to tell me if I'm talking nonsense. I see that you can send a `Zmq.Msg.t` (bigstring) instead of a string. What is the difference between a `Zmq.Msg.t` object and a binary object ? Does converting a `Yojson.Safe.t` into a `Zmq.Msg.t` will allow me to send it compressed ?

**Comment by Leonidas-from-XIV** [comment]
If you want to reduce the amount of data and your input is JSON data I would suggest looking into binary encodings of the data structure like BSON, CBOR or MessagePack, since these allow for type-safe encoding and seconding of the data (or you just Grip the string). Even better if the schema is fixed you could just transmit the payload then you get bigger savings.

`Zmq.Msg.t` allows you to send a bigstring as a payload, e.g. if you have something that is too large to fit in a string or you don't want to copy a string out of an existing bigstring for performance reasons.

I would suggest against using `Marshal` since the data is not type safe and decoding data the wrong way could lead to issues, especially if the input is controlled by untrusted users.

**Comment by MohamedLEGH** [comment]
Can I send binary encoded data with `ocaml-zmq` ? How ? (sorry if my question is stupid)

**Comment by Leonidas-from-XIV** [comment]
OCaml `string` and `bigstring` can hold binary data, they are not representing text, just bytes in memory, so you can use either of these functions to send e.g. `Protobuf` encoded payloads.

**Comment by MohamedLEGH** [comment]
Ok. I didn't know, thanks for the answer. I will investigate this. I'm closing the issue.
